version: "3.8"

services:
   mysql:
      image: mysql:8.0
      container_name: mysql-db
      restart: always
      ports:
         - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
         MYSQL_DATABASE: ${MYSQL_DATABASE:-db_product}
         MYSQL_USER: ${MYSQL_USER:-admin}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      volumes:
         - mysql-data:/var/lib/mysql
      networks:
         - internal-network

   app-product:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: app-product
      restart: always
      ports:
         - "8080:8080"
      environment:
         SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql-db:3306/db_product}
         SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-admin}
         SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-admin}
      depends_on:
         - mysql
      networks:
         - internal-network

volumes:
   mysql-data:

networks:
   internal-network:
      driver: bridge
